name: Deliver resume to webpage

# run when a commit is pushed to "source" branch
on:
  push:
    branches:
        - master

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    # checkout to the commit that has been pushed
    - name: Checkout
      uses: actions/checkout@v3
    
        # Deliver to resumeBuilder source (https://github.com/marketplace/actions/copy-files-to-another-repository)
    - name: Deliver LaTeX src files to resumeBuilder
      uses: nkoppel/push-files-to-another-repository@v1.1.3
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB_PDF }}
      with:
        source-files: 'resume/resume.pdf'
        destination-username: 'vinay-ram1999'
        destination-repository: 'vinay-ram1999.github.io'
        destination-branch: 'main'
        destination-directory: 'static/files/'
        commit-email: 'vinayramgazula@gmail.com'